name: Build ShipColor Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Kaynak kodu indir
      uses: actions/checkout@v4

    - name: OpenCPN Plugin API indir
      run: git clone --depth=1 https://github.com/OpenCPN/opencpn-libs.git opencpn_libs

    - name: wxWidgets indir ve kur
      shell: cmd
      run: |
        curl -L -o wxWidgets.7z https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.4/wxWidgets-3.2.4.7z
        7z x wxWidgets.7z -owxWidgets
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cd wxWidgets\build\msw
        msbuild wx_vc17.sln /p:Configuration=Release /p:Platform=x64 /m

    - name: CMake Configure
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DwxWidgets_ROOT_DIR="$env:GITHUB_WORKSPACE/wxWidgets" -DwxWidgets_CONFIGURATION=mswu -DOPENCPN_INCLUDE_DIR="$env:GITHUB_WORKSPACE/opencpn_libs/api-18"

    - name: CMake Build
      run: cmake --build build --config Release

    - name: DLL kaydet
      uses: actions/upload-artifact@v4
      with:
        name: shipcolor_pi_dll
        path: build/Release/shipcolor_pi.dll
